### ISSUE TITLE
Normal operations

### ISSUE THREAD

**Issue by Anobium** [MicrochipTech/XPRESS-Loader#1]
I have downloaded, compiled, programmed.  All good.

Recognized by Windows 7 as a Portable Devices/Microchip with a drive letter.   Communication is active and recognized.

However, no drive is shown in Explorer.   

This is not the same as the Xpress Board. A different object is shown in device manager and a drive is shown.

What I am doing incorrectly? or, what am I misunderstanding?

**Comment by perkyguy** [comment]
Just doing a sanity check (for you and me). 
- Cloned the repo, and compiled (no local modifcations)
- You programmed the 18LF25K50 on the Xpress board via J1
- have the USB plugged in
- the green LED is on

All that is true and the Xpress board isn't showing up as a drive in explorer (but is in device manager?)?

Does anything happen when you hold and/or release the S1 button (on the programmer side)?

**Comment by Anobium** [comment]
Impressed by response.

Cloned no mods. Correct.
Programmmed ok. I just verify.  this is a standalone chip.  I do have an Xpress board and I do not want try this until I know it works and I am in the middle of development of the training material.
USB in.  
Green LED is on.

I have the device SHOWN in device manager as shown in the screen shot below.

If I hold down the S1 button I get a reset of the USB port as expected.

The screen shot shows the drivers: Xpress board and the MyBuiltBoard :-) above. And, the comms port in Device Manager.

If I reverse the drivers swap.  Why do I have a different driver loaded?

![capture](https://cloud.githubusercontent.com/assets/17933379/13887926/6844dd74-ed36-11e5-96ac-b6f399d372b6.JPG)

**Comment by perkyguy** [comment]
I have to look into why it comes up under the Portable Devices, but that happens with my attempt to reproduce your issue as well. Do you have a "Microchip Mass Storage USB Device" under "Disk Drives" as well? Here's where I can see the device on my computer.

![image](https://cloud.githubusercontent.com/assets/4624648/13888580/64730608-ecff-11e5-83bd-acbe27317dfb.png)

**Comment by perkyguy** [comment]
Also, can you confirm that you have the part with similar connections as the board? If you're unsure, there's a schematic up on the [MPLab Xpress page](https://www.microchip.com/mplab/mplab-xpress), at the bottom under "Documentation"

**Comment by Anobium** [comment]
Thank you.  I can confirm the code works as expected.  If I had read the schematic correctly. My fault S1 pulled low not high.  A warning to all those following this path.

![capture](https://cloud.githubusercontent.com/assets/17933379/13889010/3eb18e20-ed3c-11e5-90a2-ad97251e8eae.JPG)

I can confirm this part works.   Now to hook up the 16f18855.  I have code that works in the Xpress Board so I am confident the HEX is valid.

Currently, load LED D1 flashes for load operation but nothing on the 16f as yet.  Any advice? apart from the schematic. Which I promise todo.

**Comment by Anobium** [comment]
Everything works perfectly.

I have an LED on PortA.0 flashing. Programmed from Great Cow BASIC.  [See all the example code here](https://sourceforge.net/projects/gcbasic/files/Demonstration%20Files/Vendor%20Boards/Xpress%20Evaluation%20Board/)

Works a treat. You guys have done an excellent job.  

Programming via a drag and drop.  Most excellent.

**Comment by perkyguy** [comment]
Sounds great! I had the exact same problem during a side project I was doing with this board. I'm glad there wasn't something weird going on with Windows on some computers and not others.

What was the problem with loading up the part and what was your fix (just for future knowledge)?

**Comment by Anobium** [comment]
Root cause of error: The reset line on the 18f was being pulled to the incorrect voltage. Resolved by pulled reset line to correct voltage.
